const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

const root = path.join(__dirname, '..');
const browserPanel = fs.readFileSync(path.join(root, 'src', 'renderer', 'components', 'BrowserPanel.tsx'), 'utf8');
const explorePanel = fs.readFileSync(path.join(root, 'src', 'renderer', 'components', 'ExplorePanel.tsx'), 'utf8');
const exploreSourceList = fs.readFileSync(path.join(root, 'src', 'renderer', 'components', 'explore', 'ExploreSourceList.tsx'), 'utf8');
const exploreStageNav = fs.readFileSync(path.join(root, 'src', 'renderer', 'components', 'explore', 'ExploreStageNav.tsx'), 'utf8');
const globalStyles = fs.readFileSync(path.join(root, 'src', 'renderer', 'styles', 'global.less'), 'utf8');
const appleStyles = fs.readFileSync(path.join(root, 'src', 'renderer', 'styles', 'apple.less'), 'utf8');
const exploreStyles = fs.readFileSync(path.join(root, 'src', 'renderer', 'styles', 'explore.less'), 'utf8');
const rendererMain = fs.readFileSync(path.join(root, 'src', 'renderer', 'main.tsx'), 'utf8');

assert.match(browserPanel, /type PanelMode = [^;]*'explore'/, 'PanelMode must include explore');
assert.equal((browserPanel.match(/data-tour-id="tab-/g) || []).length, 5, 'exactly five visible workspace tabs are required');
assert.match(browserPanel, /data-tour-id="tab-explore"[^\r\n]*>探索<\/button>/, 'visible Explore tab is missing');
assert.doesNotMatch(browserPanel, /tab-zhihu/, 'Zhihu must not be a workspace name');
assert.match(browserPanel, /mode === 'explore'[\s\S]*<ExplorePanel/, 'Explore panel must render from the workspace mode');

assert.match(explorePanel, />找灵感</, 'idea entry is missing');
assert.match(explorePanel, />解问题</, 'diagnosis entry is missing');
assert.match(explorePanel, /本次分析 Context/, 'diagnosis context picker is missing');
assert.match(explorePanel, /取消勾选后，该项不会进入分析/, 'context exclusion promise is missing');
assert.match(explorePanel, /需要先连接知乎开放平台/, 'safe connection wording is missing');
assert.match(explorePanel, /getExploreZhihuStatus/, 'Explore must read connection status through preload');
assert.match(explorePanel, /installExploreZhihuConnection/, 'fresh users need an explicit official CLI install action');
assert.match(explorePanel, /connection\?\.state !== 'needs_secret'[\s\S]{0,220}autoConnectionPrompted\.current = true;[\s\S]{0,100}void beginConnection\(\)/, 'missing one-shot automatic Secret prompt');
assert.match(explorePanel, /安装连接组件并继续/, 'install consent button is missing');
assert.match(explorePanel, /不会修改 PATH/, 'official user-directory install boundary is missing');
assert.match(explorePanel, /prepareExploreRequest/, 'Explore input must cross the validated Main request boundary');
assert.match(explorePanel, /saveExploreKnowledge/, 'source save must use the existing preload store');
assert.match(explorePanel, /data-tour-id="explore-saved-knowledge"/, 'saved knowledge preview is missing');
assert.match(explorePanel, /不会自动加入后续 Context/, 'manual context selection promise is missing');
assert.match(explorePanel, /findRelatedExploreKnowledge\(query, 6\)/, 'related knowledge discovery is missing');
assert.match(explorePanel, /setSelectedKnowledgeIds\(\[\]\)/, 'query changes must invalidate prior selections');
assert.match(explorePanel, /checked=\{selectedKnowledgeIds\.includes\(card\.id\)\}/, 'related knowledge requires a visible checkbox');
assert.match(explorePanel, /selectExploreKnowledgeForContext\(explicitlySelectedIds\)/, 'only explicitly selected ids may cross Main');
assert.match(explorePanel, /kind: 'knowledge'/, 'selected history must become knowledge context');
assert.match(explorePanel, /候选默认不加入分析/, 'default exclusion wording is missing');
assert.match(explorePanel, /data-tour-id="explore-verification-form"/, 'verification form is missing');
assert.match(explorePanel, /addExploreKnowledgeVerification/, 'verification must use the existing Main IPC');
assert.match(explorePanel, /!verificationSummary\.trim\(\)/, 'empty verification summary must disable submission');
assert.match(explorePanel, /saveVerification\('verified_effective'\)/, 'effective feedback action is missing');
assert.match(explorePanel, /saveVerification\('verified_ineffective'\)/, 'ineffective feedback action is missing');
assert.match(explorePanel, /不会声称硬件验证完成/, 'hardware evidence wording is missing');
assert.match(explorePanel, /onSave=\{\(source\) => void saveSource\(source\)\}/, 'source save callback must remain connected to the existing store action');
assert.match(exploreSourceList, /onClick=\{\(\) => onSave\(source\)\}/, 'source save must require a user click');
assert.doesNotMatch(explorePanel, /useEffect\([\s\S]{0,300}saveExploreKnowledge/, 'knowledge must not be saved automatically');
assert.match(explorePanel, /不会修改文件、Build、Flash 或操作串口/, 'Explore side-effect boundary is missing');
assert.match(explorePanel, /hypothesis\.projectEvidence/, 'diagnosis project evidence must be rendered');
assert.match(explorePanel, /diagnosis\.sourceConflicts/, 'diagnosis source conflicts must be rendered');
assert.match(exploreSourceList, /source\.type/);
assert.match(exploreSourceList, /source\.author/);
assert.match(exploreSourceList, /source\.excerpt/);
assert.match(exploreSourceList, /source\.url/);
assert.match(exploreStageNav, /'describe'[\s\S]*'analyze'[\s\S]*'plan'[\s\S]*'execute'/, 'four-stage navigation is missing');

assert.match(globalStyles, /grid-template-columns: repeat\(5, minmax\(0, 1fr\)\) minmax\(160px, 0\.9fr\)/);
assert.match(appleStyles, /grid-template-columns: repeat\(5, minmax\(88px, 120px\)\) minmax\(120px, 1fr\)/);
assert.match(rendererMain, /import '\.\/styles\/explore\.less'/);
assert.match(exploreStyles, /\.explore-panel\s*\{/);
assert.match(exploreStyles, /container-type:\s*inline-size/);
assert.match(exploreStyles, /@container explore \(min-width:\s*700px\)/);
assert.match(exploreStyles, /@container explore \(min-width:\s*1200px\)/);
assert.match(exploreStyles, /grid-template-columns:\s*minmax\(320px, 420px\) minmax\(0, 1fr\)/, 'wide workspace columns are missing');
assert.doesNotMatch(exploreStyles, /(?:width|max-width):\s*min\((?:760|820|960)px/, 'legacy narrow Explore width cap returned');
assert.match(exploreStyles, /:root\[data-theme="dark"\] \.explore-panel/, 'dark Explore tokens are missing');
assert.match(exploreStyles, /prefers-reduced-motion/);
assert.match(exploreStyles, /prefers-reduced-transparency/);
assert.match(exploreStyles, /prefers-contrast/);

console.log('explore UI contract passed: existing flows retained; evidence/conflicts/source detail/stages/container layouts/theme accessibility present');
