const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

const root = path.join(__dirname, '..');
const app = fs.readFileSync(path.join(root, 'src', 'renderer', 'App.tsx'), 'utf8');
const browserPanel = fs.readFileSync(path.join(root, 'src', 'renderer', 'components', 'BrowserPanel.tsx'), 'utf8');
const explorePanel = fs.readFileSync(path.join(root, 'src', 'renderer', 'components', 'ExplorePanel.tsx'), 'utf8');
const exploreSourceList = fs.readFileSync(path.join(root, 'src', 'renderer', 'components', 'explore', 'ExploreSourceList.tsx'), 'utf8');
const exploreStageNav = fs.readFileSync(path.join(root, 'src', 'renderer', 'components', 'explore', 'ExploreStageNav.tsx'), 'utf8');
const globalStyles = fs.readFileSync(path.join(root, 'src', 'renderer', 'styles', 'global.less'), 'utf8');
const appleStyles = fs.readFileSync(path.join(root, 'src', 'renderer', 'styles', 'apple.less'), 'utf8');
const exploreStyles = fs.readFileSync(path.join(root, 'src', 'renderer', 'styles', 'explore.less'), 'utf8');
const rendererMain = fs.readFileSync(path.join(root, 'src', 'renderer', 'main.tsx'), 'utf8');
const mainProcess = fs.readFileSync(path.join(root, 'src', 'main', 'index.ts'), 'utf8');
const preload = fs.readFileSync(path.join(root, 'src', 'preload', 'index.ts'), 'utf8');
const ideaEntryArt = fs.readFileSync(path.join(root, 'src', 'renderer', 'assets', 'explore-idea-guagua.png'));
const diagnosisEntryArt = fs.readFileSync(path.join(root, 'src', 'renderer', 'assets', 'explore-diagnosis-guagua.png'));

assert.match(browserPanel, /type PanelMode = [^;]*'explore'/, 'PanelMode must include explore');
assert.equal((browserPanel.match(/data-tour-id="tab-/g) || []).length, 6, 'exactly six visible workspace tabs are required');
assert.match(browserPanel, /data-tour-id="tab-explore"[^\r\n]*><Compass[^\r\n]*<span>探索<\/span><\/button>/, 'visible Explore tab and icon are missing');
assert.match(browserPanel, /data-tour-id="tab-skill-hub"/, 'Neil Skill Hub tab is missing');
assert.match(browserPanel, /http:\/\/118\.195\.247\.102\/#page-top/, 'Skill Hub URL is missing');
assert.doesNotMatch(browserPanel, /tab-zhihu/, 'Zhihu must not be a workspace name');
assert.match(browserPanel, /mode === 'explore'[\s\S]*<ExplorePanel/, 'Explore panel must render from the workspace mode');
assert.match(browserPanel, /exploreMounted[\s\S]*hidden=\{mode !== 'explore'\}/, 'Explore must stay mounted while another workspace is visible');
assert.doesNotMatch(browserPanel, /runtimeState\?\.activeProjectDir/, 'old Runtime project must not become the active Explore project');
assert.match(app, /选择工作工程/, 'cold-start project picker is missing');
assert.match(app, /activateProjectSession\(selectedProjectId\)/, 'project activation must submit a Main-issued project id');

assert.match(explorePanel, />找灵感</, 'idea entry is missing');
assert.match(explorePanel, />解问题</, 'diagnosis entry is missing');
assert.match(explorePanel, /本次分析 Context/, 'diagnosis context picker is missing');
assert.match(explorePanel, /explore-idea-guagua\.png/, 'idea entry illustration is missing');
assert.match(explorePanel, /explore-diagnosis-guagua\.png/, 'diagnosis entry illustration is missing');
assert.equal(ideaEntryArt[25], 6, 'idea entry illustration must use real RGBA transparency');
assert.equal(diagnosisEntryArt[25], 6, 'diagnosis entry illustration must use real RGBA transparency');
assert.match(explorePanel, /取消勾选后，该项不会进入分析/, 'context exclusion promise is missing');
assert.match(explorePanel, /需要先连接知乎开放平台/, 'safe connection wording is missing');
assert.match(explorePanel, /getExploreZhihuStatus/, 'Explore must read connection status through preload');
assert.match(explorePanel, /installExploreZhihuConnection/, 'fresh users need an explicit official CLI install action');
assert.match(explorePanel, /connection\?\.state !== 'needs_secret'[\s\S]{0,220}autoConnectionPrompted\.current = true;[\s\S]{0,100}void beginConnection\(\)/, 'missing one-shot automatic Secret prompt');
assert.match(explorePanel, /安装连接组件并继续/, 'install consent button is missing');
assert.match(explorePanel, /不会修改 PATH/, 'official user-directory install boundary is missing');
assert.match(explorePanel, /prepareExploreRequest/, 'Explore input must cross the validated Main request boundary');
assert.match(explorePanel, /listExploreWorkSessions/, 'project Explore history list is missing');
assert.match(explorePanel, /saveExploreWorkSession/, 'Explore work autosave is missing');
assert.match(explorePanel, /openWorkSession\(session\.mode, session\.id\)/, 'Explore history resume action is missing');
assert.match(explorePanel, /saveExploreKnowledge/, 'source save must use the existing preload store');
assert.match(explorePanel, /origin:\s*activeWorkSession[\s\S]{0,500}conversation:\s*conversation\.map/, 'saved knowledge must retain its origin Explore conversation');
assert.match(explorePanel, /deleteExploreKnowledge\(card\.id\)/, 'saved knowledge needs an explicit delete action');
assert.match(explorePanel, /查看原对话/, 'saved knowledge must expose its retained conversation');
assert.match(explorePanel, /data-tour-id="explore-saved-knowledge"/, 'saved knowledge preview is missing');
assert.match(explorePanel, /不会自动加入后续 Context/, 'manual context selection promise is missing');
assert.match(explorePanel, /findRelatedExploreKnowledge\(query, 6\)/, 'related knowledge discovery is missing');
assert.match(explorePanel, /setSelectedKnowledgeIds\(\[\]\)/, 'query changes must invalidate prior selections');
assert.match(explorePanel, /checked=\{selectedKnowledgeIds\.includes\(card\.id\)\}/, 'related knowledge requires a visible checkbox');
assert.match(explorePanel, /selectExploreKnowledgeForContext\(explicitlySelectedIds\)/, 'only explicitly selected ids may cross Main');
assert.match(explorePanel, /kind: 'knowledge'/, 'selected history must become knowledge context');
assert.match(explorePanel, /候选默认不加入分析/, 'default exclusion wording is missing');
assert.match(explorePanel, /data-tour-id="explore-verification-form"/, 'verification form is missing');
assert.match(explorePanel, /addExploreKnowledgeVerification/, 'verification must use the existing Main IPC');
assert.match(explorePanel, /!verificationSummary\.trim\(\)/, 'empty verification summary must disable submission');
assert.match(explorePanel, /saveVerification\('verified_effective'\)/, 'effective feedback action is missing');
assert.match(explorePanel, /saveVerification\('verified_ineffective'\)/, 'ineffective feedback action is missing');
assert.match(explorePanel, /不会声称硬件验证完成/, 'hardware evidence wording is missing');
assert.match(explorePanel, /onSave=\{\(source\) => void saveSource\(source\)\}/, 'source save callback must remain connected to the existing store action');
assert.match(exploreSourceList, /onClick=\{\(\) => onSave\(source\)\}/, 'source save must require a user click');
assert.doesNotMatch(explorePanel, /useEffect\([\s\S]{0,300}saveExploreKnowledge/, 'knowledge must not be saved automatically');
assert.match(explorePanel, /不会修改文件、Build、Flash 或操作串口/, 'Explore side-effect boundary is missing');
assert.match(explorePanel, /hypothesis\.projectEvidence/, 'diagnosis project evidence must be rendered');
assert.match(explorePanel, /diagnosis\.sourceConflicts/, 'diagnosis source conflicts must be rendered');
assert.match(exploreSourceList, /source\.type/);
assert.match(exploreSourceList, /source\.author/);
assert.match(exploreSourceList, /source\.excerpt/);
assert.match(exploreSourceList, /source\.url/);
assert.match(exploreStageNav, /'describe'[\s\S]*'analyze'[\s\S]*'plan'[\s\S]*'execute'/, 'four-stage navigation is missing');
assert.match(exploreStageNav, /onClick=\{\(\) => onSelect\(stage\.id\)\}/, 'reached stages must be directly selectable');
assert.match(explorePanel, /本次探索对话/, 'Explore needs a separate conversation view');
assert.match(explorePanel, /onExploreConversationMessage/, 'Explore conversation must use its own event channel');
assert.match(explorePanel, /createExploreHandoffArtifact/, 'plan completion must create project handoff artifacts');
assert.match(explorePanel, /getExploreHandoffArtifact/, 'execution view must reload project handoff artifacts');
assert.match(explorePanel, /snapshot:\s*\{[\s\S]{0,500}handoffArtifact: artifact[\s\S]{0,300}saveExploreWorkSession\(persisted\)/, 'handoff metadata must be explicitly persisted with the Explore dialogue');
assert.match(explorePanel, /status: 'execution_queued'[\s\S]{0,700}conversation: persistedConversation[\s\S]{0,400}await window\.electronAPI\.saveExploreWorkSession\(persisted\)/, 'execution confirmation must be persisted before leaving Explore');
assert.match(explorePanel, /确认提交给工程 Agent/, 'explicit engineering Agent submission action is missing');
assert.match(exploreSourceList, /打开知乎原文/, 'Zhihu source action must be explicit');
assert.match(exploreSourceList, /收藏到知识库/, 'knowledge save action must be prominent and explicit');

assert.match(globalStyles, /grid-template-columns: repeat\(5, minmax\(70px, 1fr\)\) minmax\(145px, 1\.35fr\) minmax\(160px, 1\.1fr\) auto/);
assert.match(appleStyles, /grid-template-columns: repeat\(5, minmax\(72px, 110px\)\) minmax\(145px, 180px\) minmax\(160px, 1fr\) auto/);
assert.match(browserPanel, /mode === 'workbench' \? <div className="browser-recording-controls">/, 'Skill Hub must not expose browser recording controls');
assert.match(browserPanel, /Catnip Forge · v2\.0\.0/, 'workspace release label must show v2.0.0');
assert.match(rendererMain, /import '\.\/styles\/explore\.less'/);
assert.match(exploreStyles, /\.explore-panel\s*\{/);
assert.match(exploreStyles, /container-type:\s*inline-size/);
assert.match(exploreStyles, /@container explore \(min-width:\s*700px\)/);
assert.match(exploreStyles, /@container explore \(min-width:\s*1200px\)/);
assert.match(exploreStyles, /grid-template-columns:\s*minmax\(320px, 420px\) minmax\(0, 1fr\)/, 'wide workspace columns are missing');
assert.doesNotMatch(exploreStyles, /(?:width|max-width):\s*min\((?:760|820|960)px/, 'legacy narrow Explore width cap returned');
assert.match(exploreStyles, /:root\[data-theme="dark"\] \.explore-panel/, 'dark Explore tokens are missing');
assert.match(exploreStyles, /prefers-reduced-motion/);
assert.match(exploreStyles, /prefers-reduced-transparency/);
assert.match(exploreStyles, /prefers-contrast/);
assert.match(exploreStyles, /\.explore-source-actions button \{ min-height: 36px/, 'source buttons need a stable 36px hit target');
assert.match(exploreStyles, /\.explore-idea-action-bar/, 'Idea cards need a stable footer action area');
assert.match(exploreStyles, /\.explore-entry-card--diagnosis[\s\S]{0,500}var\(--explore-cyan\)/, 'diagnosis entry needs a distinct cyan treatment');
assert.match(exploreStyles, /\.explore-entry-card--idea em[\s\S]{0,100}var\(--explore-purple\)/, 'idea entry needs a distinct purple treatment');
assert.match(exploreStyles, /\.explore-entry-illustration/, 'entry illustration layout is missing');
assert.match(mainProcess, /mainWindow = new BrowserWindow\(\{[\s\S]{0,320}frame:\s*false/, 'main window must use the custom frameless chrome');
assert.match(mainProcess, /Menu\.setApplicationMenu\(null\)/, 'native application menu must be removed');
assert.match(mainProcess, /ipcMain\.handle\('window:minimize'/, 'window minimize IPC is missing');
assert.match(mainProcess, /ipcMain\.handle\('window:toggle-maximize'/, 'window maximize IPC is missing');
assert.match(mainProcess, /ipcMain\.handle\('window:close'/, 'window close IPC is missing');
assert.match(preload, /minimizeWindow:[\s\S]{0,120}window:minimize/, 'preload minimize bridge is missing');
assert.match(preload, /toggleMaximizeWindow:[\s\S]{0,140}window:toggle-maximize/, 'preload maximize bridge is missing');
assert.match(preload, /closeWindow:[\s\S]{0,120}window:close/, 'preload close bridge is missing');
assert.match(browserPanel, /workspace-window-controls[\s\S]{0,900}minimizeWindow[\s\S]{0,400}toggleMaximizeWindow[\s\S]{0,400}closeWindow/, 'functional custom window controls are missing');
assert.match(browserPanel, /catnip-app-icon\.png/, 'the supplied Catnip app icon must be used by the workspace brand');
assert.match(browserPanel, /workspace-brand workspace-shell-box[\s\S]{0,700}workspace-nav-tabs workspace-shell-box[\s\S]{0,1800}workspace-shell-actions workspace-shell-box/, 'the top shell must remain split into brand, tab, and action surfaces');
assert.match(browserPanel, /data-tour-id="tab-tasks"[\s\S]{0,300}<span>任务管理器<\/span>/, 'task manager label must be complete');

console.log('explore UI contract passed: existing flows retained; evidence/conflicts/source detail/stages/container layouts/theme accessibility present');
